name: Deployment to development

on:
  push:
    branches:
      - development
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            git config --global --add safe.directory /opt/lampp/htdocs/BestPro
            cd /opt/lampp/htdocs/BestPro
            pwd
            git pull origin development
            git status
      - name : restart lampp service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            sudo systemcl restart xampp.service