name: Deployment to production

on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            sudo git config --global --add safe.directory /opt/lampp/htdocs/BestPro-prod
            cd /opt/lampp/htdocs/BestPro-prod
            sudo git pull origin main
            sudo /usr/bin/chown -R daemon:daemon .
      - name : restart lampp service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          port: 22
          script: |
            sudo systemcl restart xampp.service